### ISSUE TITLE
Strand-ambiguity and multiallelic variant filters in GWAS_QC method

### ISSUE THREAD

**Issue by froehlichbenedikt** [borangao/MESuSiE#11]
Dear Boran,

my coworkers and me are struggling to comprehend some filters as applied by your "GWAS_QC" method in the preprocessing pipeline. As implemented, your method removes all A/T and G/C variantes due to possible strand ambiguity. However, we found that as long as the allele frequencies are not close to 0.5, there is no danger of confusing both strands. 
Secondly, with the second step in the same method, by filtering for variants based on the total amount of letters used in the encoding of the variant, wouldn't it filter for indels, rather than multiallelic variants? 

It appears to us that these filters remove possibly causal variants that have no problematic encoding, except for variants with allele frequency close to 0.5, and one could improve upon the results by replacing these filters with a filter removing only A/T and G/C variants with allele frequencies close to 0.5. 
If this is not the case, could you expand why these filters are necessary for the preprocessing step, and what could go possibly wrong if these filters are not employed? 

Thank you so much in advance!
All the best, Benedikt

**Comment by borangao** [comment]
Dear Benedikt

Thank you for your interest in MESuSiE.

If you are confident about not confusing strands, you can safely include A/T and G/C SNPs in your analysis. To facilitate this, I have re-implemented the GWAS_QC function, allowing you to bypass strand-based filtering by setting the rm_strand = FALSE option. Similarly, you can avoid filtering out indels by using rm_indel = FALSE.

The confusion was likely caused by comments in the original code, which I have now updated for better clarity. While my previous experiments were based on datasets with A/T and G/C SNPs removed, it should be fine to include them as long as you are confident about the strand information.

I hope this helps! Please feel free to reach out if you have any further questions or need assistance.

Best,
Boran

**Comment by froehlichbenedikt** [comment]
Dear Boran,

thank you for your fast and helpful reply!
This clarifies all of my questions,

thank you very much!
