### ISSUE TITLE
Signals or credible sets identified by SuSiE but not by MeSuSiE

### ISSUE THREAD

**Issue by Xi-Cao** [borangao/MESuSiE#9]
Hi there! Thank you for your work on trans-ancestry fine-mapping. I’m a bit confused about the comparison of causal signals between MeSuSiE and SuSiE.

In the real data analysis section of your article, you mentioned that "most of the SuSiE-identified shared signals (41 out of 43) are also identified by MeSuSiE." What about the remaining two signals identified by SuSiE but not by MeSuSiE? How can we judge the reliability of these two signals and others in similar situations (signals or credible sets), considering that your method has better performance than SuSiE?

Thanks ,
xicao

**Comment by borangao** [comment]
Dear Xicao,

I missed out your email as I am currently in transition into a new position
at purdue. You can reach me at ***@***.***
Regarding your questions, "most of the SuSiE-identified shared signals (41
out of 43) are also identified by MeSuSiE." What about the remaining two
signals identified by SuSiE but not by MeSuSiE? How can we judge the
reliability of these two signals and others in similar situations (signals
or credible sets), considering that your method has better performance than
SuSiE?

Overall MESuSiE can detect more shared causal signals based on PIP cutoffs,
it does not necessarily mean the signals detected by SuSiE are wrong. By
further lowing down the PIP threshold, MESuSiE may identify all signals
detected by SuSiE. I would rather view it as a power issue rather than
false discoveries. Hope this helps.

Best,
Borna
Boran Gao
Ph.D. Candidate in Biostatistics
MPH Epidemiology
MS Biostatistics
University of Michigan School of Public health
7345462396

**Comment by Xi-Cao** [comment]
Thanks for your reply!

I think your answer quite helpful. It’s also interesting to note that a similar signal was discussed in the recent cross-population fine-mapping study, SuSiEx. The authors found that this signal was a low-quality variant located in a low-complexity region. They further pointed out that 'a non-trivial proportion of credible sets from single-population fine-mapping that were estimated to have lower maximum PIPs by SuSiEx may be attributed to quality-related concerns.' Could this provide an additional perspective on the issue?

Additionally, thank you for providing your email; however, it seems to have been blocked by "****"

Thanks,
xicao

**Comment by Xi-Cao** [comment]
Dear Dr. Gao,




Thanks for your reply! I think your answer quite helpful. 




It’s also interesting to note that a similar signal was discussed in the recent cross-population fine-mapping study, SuSiEx. The authors found that this signal was a low-quality variant located in a low-complexity region. They further pointed out that 'a non-trivial proportion of credible sets from single-population fine-mapping that were estimated to have lower maximum PIPs by SuSiEx may be attributed to quality-related concerns.' Could this provide an additional perspective on the issue? Considering that MeSuSiE has performed some QC steps for the variants.




Thanks,
xicao




-----原始邮件-----
发件人:"Boran Gao" ***@***.***>
发送时间:2024-11-01 21:44:29 (星期五)
收件人: borangao/MESuSiE ***@***.***>
抄送: Xi-Cao ***@***.***>, "State change" ***@***.***>
主题: Re: [borangao/MESuSiE] Signals or credible sets identified by SuSiE but not by MeSuSiE (Issue #9)

**Comment by borangao** [comment]
The argument in SuSiEX would more point to the higher power of detecting
shared signal, as you could think those true shared signals have a lower
maximum PIP by single ancestry SuSiE. It is not easy to argue in the other
way that those detected by SuSIE are false signals.  Hope this helps.

Best,
Boran
Boran Gao
Ph.D. Candidate in Biostatistics
MPH Epidemiology
MS Biostatistics
University of Michigan School of Public health
7345462396

**Comment by Xi-Cao** [comment]
Dear Dr. Gao,


I understand. Thanks a lot for your reply! 

best,
xicao


发件人："Boran Gao" ***@***.***>
发送日期：2024-11-02 01:45:04
收件人："borangao/MESuSiE" ***@***.***>
抄送人：
主 题：Re: [borangao/MESuSiE] Signals or credible sets identified by SuSiE but not by MeSuSiE (Issue #9)
